url: "https://testing.petrovski.cc"
baseurl: "/"
title: "TauPau Engineering" # the name of your site, e.g. ACME Corp.
collections:
  - previews
  - categories
  - projects

highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
